version: "3.2"
services:
  flask:
    build:
      context: './flask/'
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:5000"
    volumes:
      - ${PROJECT_ROOT}/:/app
    container_name: flask
  mysql:
    build:
      context: './mariaDB/'
    restart: always
    ports:
      - "3306:3306"
    volumes:
            - data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql
networks:
  frontend:
  backend:
volumes:
    data:
